		<script language="JavaScript" type="text/javascript">
		var myMenu =
		[
					['<img src="../img/arrow.png" />','  Inicio  ','index.php',null,'Pagina Principal'],
			_cmSplit,			
				['<img src="../img/arrow.png" />',' Registrar Alumnos',null,null,'Registrar Alumnos',					
				['<img src="../img/arrow.png" />',' Registrar Alumnos','registrar.php',null,'Registrar Alumnos'],
				['<img src="../img/arrow.png" />',' Registrar Alumnos Basico','basico.php',null,'Registrar Alumnos Basico'],
				['<img src="../img/arrow.png" />',' Registrar Alumnos Avanzado','avanzado.php',null,'Registrar Alumnos Avanzado'],		
				['<img src="../img/arrow.png" />',' Buscar Alumnos','buscar.php',null,'Buscar Alumnos'],
				],
			_cmSplit,			
				['<img src="../img/arrow.png" />',' Registrar Docentes',null,null,'Registrar Docentes',					
				['<img src="../img/arrow.png" />',' Registrar Docentes','docente.php',null,'Registrar Docentes'],		
				['<img src="../img/arrow.png" />',' Buscar Docentes','buscarx.php',null,'Buscar Docentes'],		
				],
			_cmSplit,			
				['<img src="../img/arrow.png" />',' Registrar Materias',null,null,'Registrar Materias',					
				['<img src="../img/arrow.png" />',' Registrar Materias','materia.php',null,'Registrar Materias'],		
				['<img src="../img/arrow.png" />',' Buscar Materias','buscarm.php',null,'Buscar Materias'],		
				],
			_cmSplit,			
				['<img src="../img/arrow.png" />',' Notas Pregrado',null,null,'Pregrado',					
				['<img src="../img/arrow.png" />',' Primer Año','nprimero.php',null,'Primer Año'],					
				['<img src="../img/arrow.png" />',' Segundo Año','nsegundo.php',null,'Primer Año'],					
				['<img src="../img/arrow.png" />',' Tercer Año','ntercero.php',null,'Primer Año'],		
				],
			_cmSplit,			
				['<img src="../img/arrow.png" />',' Notas Post Grado',null,null,'Post Grado',					
				['<img src="../img/arrow.png" />',' Curso Basico','nbasico.php',null,'Curso Basico'],					
				['<img src="../img/arrow.png" />',' Curso Avanzado','navanzado.php',null,'Curso Avanzado'],	
				],
			_cmSplit,			
				['<img src="../img/arrow.png" />',' Reportes',null,null,'Reportes',										
				['<img src="../img/arrow.png" />',' RR.NN. AA. Primer Año','primero.php',null,'RR.NN. AA. Primer Año'],
				['<img src="../img/arrow.png" />',' RR.NN. AA. Segundo Año','segundo.php',null,'RR.NN. AA. Segundo Año'],
				['<img src="../img/arrow.png" />',' RR.NN. AA. Tercero Año','tercero.php',null,'RR.NN. AA. Tercero Año'],
				['<img src="../img/arrow.png" />',' RR.NN. AA. Basico','basicoa.php',null,'RR.NN. AA. Basico'],
				['<img src="../img/arrow.png" />',' RR.NN. AA. Avanzado','avanzadoa.php',null,'RR.NN. AA. Avanzada'],		
				['<img src="../img/arrow.png" />',' Reporte Individual de Notas','individual.php',null,'Reporte Individual de Nots'],
				['<img src="../img/arrow.png" />',' Reporte Individual de Disciplina','disciplina.php',null,'Reporte Individual de Disciplina'],
				],
			_cmSplit,			
				['<img src="../img/arrow.png" />',' Reporte Historico',null,null,'Reporte Historico',					
				['<img src="../img/arrow.png" />',' Reporte Por Promocion','promocion.php',null,'Reporte Por Promocion'],					
				['<img src="../img/arrow.png" />',' Historial Academico','historiala.php',null,'Historial Academico'],
				['<img src="../img/arrow.png" />',' Reporte de Disciplina','historiald.php',null,'Reporte de Disciplina'],
				],
		];
		cmDraw ('myMenuID', myMenu, 'hbr', cmThemeOffice, 'ThemeOffice');
		</script>
